---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: example-app
  namespace: example-app
spec:
  destination:
    name: example-app
  sources:
  - name: api-gateway
    action: allow